### ISSUE TITLE
nicehash excavator

### ISSUE THREAD

**Issue by KlopSS** [vertcoin-project/p2pool-vtc#21]
Please update you stratum for https://github.com/nicehash/excavator
Nice miner for Vertcoin, but not working with p2pool. Yiimp/nice/suprnova - worked.
![2018-01-06 01-45-03](https://user-images.githubusercontent.com/35155145/34633589-b7a07efe-f285-11e7-8b6a-731fc10aa02d.png)

**Comment by stevecastaneda** [comment]
Since 1.5.0a, Excavator is no longer compatible with anything but Nicehash stratums.

https://github.com/nicehash/excavator/releases/tag/v1.5.0a
