### ISSUE TITLE
Vertcoin.dat issue

### ISSUE THREAD

**Issue by skitzo2000** [vertcoin-project/p2pool-vtc#49]
I was having difficulty getting the run_p2pool.py script to run.  It kept complaining about looking for the wallet.dat.  My wallet is in the default .vertcoin directory.  I could run p2pool from there, but then the web interface would break(Resource not available).  I also tried using the --datadir flag, but that seems to only effect the pool data.

The script seem to only work when the wallet.dat file is in the same directory as the script.  I was able to tweak the vertcoin.py and vertcoin_test.py to use a full path as a hack.  But an option to specify the .dat file location would be nice.  Or at the least have it look in the default ~/.vertcoin directory would be helpful.

I can work on creating a flag or make it look in the default .vertcoin directory is their a preffered method?  Or did I just set something up wrong?

**Comment by vertiond** [comment]
It looks for verthash.dat in the root p2pool-vtc folder by default.  I would symlink it from your Vertcoin-Core data directory.
